name: CI

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Install UV and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv==0.5.7
          uv pip install -e '.[test,dev]' --system

      - name: Format code
        run: |
          isort src/
          black src/

      - name: Lint code
        run: |
          bandit -r src/ -c pyproject.toml
          ruff check src/
          pylint src/
          mypy src/

      - name: Test code
        run: |
          pytest -v

  docker-build-and-run:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Generate Docker environment file
        run: |
          make dotenv-docker

      - name: Build and run Docker compose
        run: |
          docker compose up -d --build

      - name: Verify Application Health
        run: |
          timeout 10s bash -c '
            while ! curl -sf http://0.0.0.0:9999/api/v1/; do
              sleep 1
            done
          '

      - name: Test Signup Handler
        run: |
          timeout 10s bash -c "
            while ! curl -sf -X POST \
              'http://0.0.0.0:9999/api/v1/account/signup' \
              -H 'accept: application/json' \
              -H 'Content-Type: application/json' \
              -d '{
              \"username\": \"string\",
              \"password\": \"string\"
            }'; do
              sleep 1
            done
          "
